#!/bin/bash
set -e

case "${1}" in
    triggered)
        for trigger in ${2}; do
            # Qubes menus prefix
            case "${trigger}" in
                /etc/kde/env/env.sh)
                    sed -i 's|XDG_MENU_PREFIX="kde4-"|XDG_MENU_PREFIX="kde4-qubes-"|g' /etc/kde/env/env.sh
                    ;;

                /etc/xdg/plasma-workspace/env/env.sh)
                    sed -i 's|XDG_MENU_PREFIX="kf5-"|XDG_MENU_PREFIX="kf5-qubes-"|g' /etc/xdg/plasma-workspace/env/env.sh
                    ;;

            esac
        done
        exit 0
        ;;

    *)
        echo "nothing to be done for \`${1}'" >&2
        exit 0
        ;;
esac

exit 0

# vim: set ts=4 sw=4 sts=4 et :